<?php

/**
 * @file
 * Instagram formatter module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_theme().
 *
 * {@inheritdoc}
 */
function instagram_formatter_theme() {
  return [
    'instagram_formatter_post' => [
      'variables' => [
        'data' => NULL,
      ],
      'template' => 'instagram-block',
    ],
  ];
}

/**
 * Implements hook_help().
 */
function instagram_formatter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the instagram_formatter module.
    case 'help.page.instagram_formatter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Instagram block that displays Instagram posts.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme_suggestions_HOOK_alter().
 */
function instagram_formatter_theme_suggestions_instagram_formatter_post_alter(array &$suggestions, array $variables) {
  $suggestions[] = '';
}
